In [1]:
import numpy as np

In [4]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
arr[8]

8

In [6]:
arr[0:5]

array([0, 1, 2, 3, 4])

In [8]:
arr[0]=9

In [9]:
arr

array([9, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
arr[0:5]=9
arr

array([9, 9, 9, 9, 9, 5, 6, 7, 8, 9])

In [11]:
data = arr[0:5]

In [12]:
data

array([9, 9, 9, 9, 9])

In [13]:
data[:]=99
data


array([99, 99, 99, 99, 99])

In [14]:
arr

array([99, 99, 99, 99, 99,  5,  6,  7,  8,  9])

In [15]:
arr_2d = np.array(([5,10,15],[20,25,30],[35,40,45]))

In [16]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [17]:
arr_2d[1]

array([20, 25, 30])

In [18]:
arr_2d[1][0]

20

In [19]:
arr_2d[1,0]

20

In [20]:
arr_2d[0:2,1:3]

array([[10, 15],
       [25, 30]])

In [21]:
arr_2d[:2,1:]

array([[10, 15],
       [25, 30]])

In [22]:
nilai = np.arange(1,11)
nilai

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [23]:
nilai > 5

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [24]:
nilai[nilai>5]

array([ 6,  7,  8,  9, 10])

In [25]:
nilai*nilai

array([  1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [26]:
nilai+nilai

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [27]:
nilai-nilai

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [28]:
nilai/nilai

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])