In [7]:
import numpy as np

In [8]:
data = [1,2,3]
data

[1, 2, 3]

In [9]:
np.array(data)

array([1, 2, 3])

In [11]:
np.arange(0, 10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [12]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [13]:
np.linspace(0,10,3)

array([ 0.,  5., 10.])

In [14]:
np.linspace(0,10,50)

array([ 0.        ,  0.20408163,  0.40816327,  0.6122449 ,  0.81632653,
        1.02040816,  1.2244898 ,  1.42857143,  1.63265306,  1.83673469,
        2.04081633,  2.24489796,  2.44897959,  2.65306122,  2.85714286,
        3.06122449,  3.26530612,  3.46938776,  3.67346939,  3.87755102,
        4.08163265,  4.28571429,  4.48979592,  4.69387755,  4.89795918,
        5.10204082,  5.30612245,  5.51020408,  5.71428571,  5.91836735,
        6.12244898,  6.32653061,  6.53061224,  6.73469388,  6.93877551,
        7.14285714,  7.34693878,  7.55102041,  7.75510204,  7.95918367,
        8.16326531,  8.36734694,  8.57142857,  8.7755102 ,  8.97959184,
        9.18367347,  9.3877551 ,  9.59183673,  9.79591837, 10.        ])

In [15]:
np.random.rand(3)

array([0.59556903, 0.06588836, 0.73151012])

In [16]:
np.random.rand(3,3)

array([[0.42457469, 0.22496396, 0.41215465],
       [0.14740917, 0.05983951, 0.50107303],
       [0.08806432, 0.84978858, 0.44359566]])

In [17]:
np.random.randn(3,3)

array([[-0.41836072,  0.20310841, -0.65271958],
       [-1.01349145, -1.56690341,  0.04114662],
       [ 0.07854283,  1.33254154,  1.13699542]])

In [18]:
np.random.randint(1,50)

8

In [31]:
np.random.randint(1,50,10)

array([36, 40, 16, 33, 11, 48, 27, 16, 39,  5])

In [20]:
arr = np.arange(25)

In [21]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [35]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [23]:
arr.max()

24

In [24]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [25]:
arr.min()

0

In [26]:
arr.argmax()

24

In [28]:
arr.argmin()

0

In [29]:
arr.sum()

300