In [12]:
import numpy as np

In [13]:
arrint = np.arange(10,50)
arrint

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

In [14]:
arr = np.arange(10,50,2)
arr

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48])

In [46]:
arr = np.arange(9)
arr
arr.reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [16]:
np.random.rand(25)

array([0.69582869, 0.44745681, 0.11591748, 0.87588237, 0.40080045,
       0.83994877, 0.93357063, 0.97130779, 0.40292631, 0.90998918,
       0.51208345, 0.84403381, 0.50339797, 0.68881718, 0.65321106,
       0.20561307, 0.33440638, 0.11636043, 0.91179226, 0.67718245,
       0.59511431, 0.1459767 , 0.65629221, 0.65431736, 0.62037739])

In [17]:
arr_2 = np.array((
    [0,1,3,4,5],
    [6,7,8,9,10],
    [11,12,13,14,15],
    [16,17,18,19,20],
    [21,22,23,24,25]))
arr_2

array([[ 0,  1,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [62]:
data = arr_2[2:5,1:5]
data

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

In [26]:
arr_2[3][4]

20

In [27]:
arr_2.max()

25

In [28]:
arr_2.min()

0

In [29]:
arr_2.argmax()

24

In [47]:
arr_2.argmin()

0

In [48]:
arr_2

array([[ 0,  1,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [65]:
data = arr_2[2:4,0:5]
data[data < 21]

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [73]:
arr = arr_2[arr_2>10]
arr[arr<=20]

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])